auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  # kubernetes image
  k8s.gcr.io/kube-apiserver: sundewang/kube-apiserver
  k8s.gcr.io/kube-scheduler: sundewang/kube-scheduler
  k8s.gcr.io/kube-proxy: sundewang/kube-proxy
  k8s.gcr.io/kube-controller-manager: sundewang/kube-controller-manager
  k8s.gcr.io/etcd: sundewang/etcd
  coredns/coredns: sundewang/coredns
  k8s.gcr.io/pause: sundewang/pause
  
  
  
