auth:
  registry.hub.docker.com:
    username: USERNAME
    password: PASSWORD
images:
  # nginx-ingres
  #k8s.gcr.io/ingress-nginx/controller: sundewang/ingress-nginx-controller
  #k8s.gcr.io/ingress-nginx/kube-webhook-certgen: sundewang/kube-webhook-certgen
  # kubernetes image
  registry.k8s.io/kube-apiserver: sundewang/kube-apiserver
  registry.k8s.io/kube-scheduler: sundewang/kube-scheduler
  registry.k8s.io/kube-proxy: sundewang/kube-proxy
  registry.k8s.io/kube-controller-manager: sundewang/kube-controller-manager
  registry.k8s.io/etcd: sundewang/etcd
  registry.k8s.io/coredns/coredns: sundewang/coredns
  registry.k8s.io/pause: sundewang/pause
  
  
  
